Specify Fastly provider
Otherwise `plan` fails with:

```
Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/fastly -> fastly/fastly
```

`fastly/fastly` looks like the right one to use, based on
https://registry.terraform.io/providers/fastly/fastly/latest/docs