Fix "Invalid value for module argument" error
The `plan` was failing with errors like:

```
Error: Invalid value for module argument

  on main.tf line 673, in module "backend_public_lb_rules":
 673:   listener_arn                     = "${module.backend_public_lb.load_balancer_ssl_listeners[0]}"

The given value is not suitable for child module variable "listener_arn"
defined at ../../modules/aws/lb_listener_rules/main.tf:24,1-24: string
required.
```