Wrap 'egress_ips' in 'toset' function
This forces all elements in the array to be a string, and removes
duplicate values:
https://developer.hashicorp.com/terraform/language/v1.1.x/functions/toset

This is an attempt to fix the following `plan` of `infra-mirror-bucket`
in Staging:

```
Error: Incorrect attribute value type

  on mirror-read-policy.tf line 100, in data "aws_iam_policy_document" "s3_mirror_read_policy_doc":
 100:       values   = local.egress_ips
    |----------------
    | local.egress_ips is tuple with 4 elements

Inappropriate value for attribute "values": element 3: string required.
```