Bump Lambda's Python version from 3.6 to 3.8
The Terraform `apply` was failing with:

```
Error: Error applying plan:

1 error occurred:
	* aws_lambda_function.transition_executor: 1 error occurred:
	* aws_lambda_function.transition_executor: Error modifying Lambda Function Code govuk-integration-transition: InvalidParameterValueException: The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions.
{
  Message_: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions.",
  Type: "User"
}
```

Python 3.9 isn't available on our systems yet, so using 3.8.