Remove provider versions where not needed
Otherwise Terraform `plan` was failing with:

```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints ~> 3.76, 2.46.0, 2.46.0,
2.46.0
```

NB the `archive` one doesn't appear to be being used anwyay.