Bump Terraform version from 0.12 to 0.13 and specify AWS provider
The NodeJS runtime is incompatible with the version of
terraform-provider-aws we were using, leading to this error on a
`plan`:

```
Error: expected runtime to be one of [dotnetcore1.0 dotnetcore2.0 dotnetcore2.1 dotnetcore3.1 go1.x java8 java11 nodejs4.3 nodejs4.3-edge nodejs6.10 nodejs8.10 nodejs10.x nodejs12.x provided python2.7 python3.6 python3.7 python3.8 ruby2.5 ruby2.7], got nodejs16.x

  on waf.tf line 93, in resource "aws_lambda_function" "aws_waf_log_trimmer":
  93: resource "aws_lambda_function" "aws_waf_log_trimmer" {
```

[v3.75.2](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.75.2)
introduces the `nodejs16.x` runtime to Lambdas, so we bump to at
least version 3.76 to ensure the runtime is available.
This also required updating Terraform to v0.13.6.