Fix "Incorrect attribute value type" error
```
Error: Incorrect attribute value type

  on ../../modules/aws/alarms/elb/main.tf line 157, in resource "aws_cloudwatch_metric_alarm" "elb_httpcode_elb_5xx":
 157:   alarm_actions       = ["${var.alarm_actions}"]

Inappropriate value for attribute "alarm_actions": element 0: string required.
```